name: Expo APK Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Setup Expo CLI
      run: npm install -g @expo/cli eas-cli
    
    - name: Install dependencies
      run: npm install
    
    - name: Create app.json for Expo
      run: |
        cat > app.json << 'EOF'
        {
          "expo": {
            "name": "Ludo Game",
            "slug": "ludo-game",
            "version": "1.0.0",
            "orientation": "portrait",
            "icon": "./assets/icon.png",
            "userInterfaceStyle": "light",
            "splash": {
              "image": "./assets/splash.png",
              "resizeMode": "contain",
              "backgroundColor": "#ffffff"
            },
            "platforms": ["android"],
            "android": {
              "adaptiveIcon": {
                "foregroundImage": "./assets/adaptive-icon.png",
                "backgroundColor": "#FFFFFF"
              },
              "package": "com.ludogame.app"
            },
            "web": {
              "favicon": "./assets/favicon.png"
            }
          }
        }
        EOF
    
    - name: Create dummy assets
      run: |
        mkdir -p assets
        # Create a simple colored square as placeholder
        convert -size 1024x1024 xc:blue assets/icon.png || echo "ImageMagick not available, skipping icon"
        convert -size 1024x1024 xc:green assets/splash.png || echo "ImageMagick not available, skipping splash"
        convert -size 1024x1024 xc:red assets/adaptive-icon.png || echo "ImageMagick not available, skipping adaptive-icon"
        convert -size 32x32 xc:yellow assets/favicon.png || echo "ImageMagick not available, skipping favicon"
    
    - name: Build APK with Expo
      run: |
        npx expo install --fix
        npx expo export --platform android
        npx expo build:android --type apk --non-interactive || echo "Expo build failed, trying alternative"
    
    - name: Alternative - Create simple HTML5 game
      if: failure()
      run: |
        mkdir -p dist
        cat > dist/ludo-game.html << 'EOF'
        <!DOCTYPE html>
        <html>
        <head>
            <title>Ludo Game</title>
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <style>
                body { margin: 0; padding: 20px; font-family: Arial, sans-serif; text-align: center; }
                .game-board { width: 300px; height: 300px; background: #f0f0f0; margin: 20px auto; border: 2px solid #333; }
                button { padding: 10px 20px; margin: 10px; background: #007bff; color: white; border: none; border-radius: 5px; }
            </style>
        </head>
        <body>
            <h1>🎲 Ludo Game</h1>
            <div class="game-board">Game Board</div>
            <button onclick="alert('Game Started!')">Start Game</button>
            <p>Your Ludo game will be here!</p>
        </body>
        </html>
        EOF
    
    - name: Upload build output
      uses: actions/upload-artifact@v4
      with:
        name: ludo-game-build
        path: |
          dist/
          *.apk
        retention-days: 30
