name: Minimal APK Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Setup JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: '11'
    
    - name: Install Node dependencies
      run: npm install --force
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        api-level: 33
        build-tools: 33.0.0
    
    - name: Accept Android licenses
      run: yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
    
    - name: Make gradlew executable
      run: chmod +x android/gradlew
    
    - name: Generate debug keystore
      run: |
        mkdir -p android/app
        keytool -genkey -v -keystore android/app/debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Android Debug,O=Android,C=US"
    
    - name: Build Debug APK (easier than release)
      run: |
        cd android
        ./gradlew assembleDebug --stacktrace --info
    
    - name: List build outputs
      run: find android/app/build/outputs -name "*.apk" -type f
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: ludo-debug-apk
        path: android/app/build/outputs/apk/debug/app-debug.apk
        retention-days: 30
