name: Simple APK Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'
    
    - name: Install npm dependencies
      run: npm install
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
    
    - name: Create gradle wrapper
      run: |
        cd android
        gradle wrapper
    
    - name: Build APK
      run: |
        cd android
        chmod +x gradlew
        ./gradlew assembleRelease
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: android/app/build/outputs/apk/release/*.apk
